### ISSUE TITLE
Question about situation when there are multiple XHR requests

### ISSUE THREAD

**Issue by ChaunceyKiwi** [jtassin/pending-xhr-puppeteer#1]
https://github.com/jtassin/pending-xhr-puppeteer/blob/ea052c173c5633ae46975197ed7721d999c4e150/src/index.js#L9-L18

From my understanding of code, it seems that if there are two pending XHRs, only the first one will trigger a creation of promise and link its resolve() to resolver. The second one will not have its own promise object and resolver. How can you make sure each request is handled properly in this way. Correct me if I am wrong :)

**Comment by jtassin** [comment]
Hi @ChaunceyKiwi thx a lot for your feedback.
You are right, there is a problem there. I'll fix it.
