### ISSUE TITLE
Bug: pending-xhr-puppeteer@2.2.0 missing "waitOnceForAllXhrFinished" due to forgot building to lib folder

### ISSUE THREAD

**Issue by jf3096** [jtassin/pending-xhr-puppeteer#140]
once I install this library, i found that "waitOnceForAllXhrFinished" is missing in pending-xhr-puppeteer/lib/index.js but found in src/index.ts.

BTW, could u pls remove ONLY include lib files when publish to npm? Thank you!

**Comment by jtassin** [comment]
Thx for feedback everything is fixed in `2.3.2`
