### ISSUE TITLE
Edge Cases?

### ISSUE THREAD

**Issue by shirshak55** [jtassin/pending-xhr-puppeteer#37]
Lets say ajax request happen after clicking button after 3-5 sec ? Do it work ? Or this is based on particular instant like because sometime ajax can delay lets say after 2-3 sec and this plugin may check before ajax happen?

I was trying to use as below code usually don't work. Thanks.

```

await Promise.all([page.waitForNavigation({waitUntil: 'networkidle2'})], btnHandler.click())

```

Let me know if we have other solutions too :)

**Comment by jtassin** [comment]
Hi @shirshak55 .

There should be no problem for a usage on a button click.
As soon as you execute : 

```javascript
const pendingXHR = new PendingXHR(page);
```

Before the action, the xhr will be catched.

**Comment by shirshak55** [comment]
@jtassin thanks little panda :) Yea seems like this logic will work :D
