### ISSUE TITLE
Provide TypeScript typings

### ISSUE THREAD

**Issue by rwu823** [jtassin/pending-xhr-puppeteer#55]
Hey, this is a great job, and resolve my problems. I hope you can provide typings of TypeScript.

**Comment by jtassin** [comment]
Hi @rwu823 types are available since the 2.0.0 version.
Are you up to date ?

**Comment by rwu823** [comment]
Yes, I'm using 2.0.0.

According  to `package.json`:
https://github.com/jtassin/pending-xhr-puppeteer/blob/master/package.json#L7

The typing file is mapping to `lib/index.d.ts`

But I didn't see yet.
https://yarnpkg.com/en/package/pending-xhr-puppeteer?files

**Comment by jtassin** [comment]
You're right, I'll have a look at it.

Thx for your feedback !
